/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import interfaces.ICarModelFactory;
import interfaces.ICreator;
import interfaces.IPrototype;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import util.PluginLoader;

/**
 *
 * @author emersant
 */
public class CreateFactoryPrototype extends javax.swing.JFrame {
    private AbstractFactoryCar retorno;
    private AbstractFactory abstractFactory;
    private IPrototype prototype;
    private Mensagem modalMensagem = null;
    /**
     * Creates new form NovoJFrame
     */
    public CreateFactoryPrototype() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        btnRemoverUm = new javax.swing.JButton();
        btnRemoverTodos = new javax.swing.JButton();
        btnAdicionarUm = new javax.swing.JButton();
        lblAdicionar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaSelecionados = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPrototypes = new javax.swing.JList<>();
        lblPrototypes = new javax.swing.JLabel();
        lblPrototypes1 = new javax.swing.JLabel();
        btnCriarFabrica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRemoverUm.setText("<");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnRemoverUm, org.jdesktop.beansbinding.ELProperty.create("Remover selecionado"), btnRemoverUm, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        btnRemoverUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverUmActionPerformed(evt);
            }
        });

        btnRemoverTodos.setText("<<");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnRemoverTodos, org.jdesktop.beansbinding.ELProperty.create("Remover todos"), btnRemoverTodos, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        btnRemoverTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverTodosActionPerformed(evt);
            }
        });

        btnAdicionarUm.setText(">");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnAdicionarUm, org.jdesktop.beansbinding.ELProperty.create("Adicionar aos selecionados"), btnAdicionarUm, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        btnAdicionarUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarUmActionPerformed(evt);
            }
        });

        lblAdicionar.setText("Adicionar tipos de produtos:");

        listaSelecionados.setModel(new DefaultComboBoxModel<>());
        listaSelecionados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaSelecionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaSelecionadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaSelecionados);

        listaPrototypes.setModel(new DefaultComboBoxModel<>());
        listaPrototypes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaPrototypes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPrototypesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaPrototypes);

        lblPrototypes.setText("Prototypes:");

        lblPrototypes1.setText("Selecionados:");

        btnCriarFabrica.setText("Criar Fábrica");
        btnCriarFabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarFabricaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPrototypes)
                                        .addGap(157, 157, 157))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnRemoverTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAdicionarUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnRemoverUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrototypes1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnCriarFabrica)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrototypes)
                    .addComponent(lblPrototypes1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdicionarUm)
                        .addGap(42, 42, 42)
                        .addComponent(btnRemoverUm)
                        .addGap(41, 41, 41)
                        .addComponent(btnRemoverTodos))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(26, 26, 26)
                .addComponent(btnCriarFabrica)
                .addGap(24, 24, 24))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverUmActionPerformed
        removerSelecionado();
    }//GEN-LAST:event_btnRemoverUmActionPerformed

    private void btnRemoverTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverTodosActionPerformed
        removerTodos();
    }//GEN-LAST:event_btnRemoverTodosActionPerformed

    private void btnAdicionarUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarUmActionPerformed
        abrirModal(this);
    }//GEN-LAST:event_btnAdicionarUmActionPerformed
    private void listaPrototypesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPrototypesMouseClicked
        if(evt.getButton() == 1) {
            if(evt.getClickCount() > 1) {
                adicionarSelecionado();
            }
        }
    }//GEN-LAST:event_listaPrototypesMouseClicked

    private void listaSelecionadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaSelecionadosMouseClicked
        if(evt.getButton() == 1) {
            if(evt.getClickCount() > 1) {
                removerSelecionado();
            }
        }
    }//GEN-LAST:event_listaSelecionadosMouseClicked

    private void btnCriarFabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarFabricaActionPerformed
        this.abstractFactory.adicionar(prototype);
        retornarHost();
    }//GEN-LAST:event_btnCriarFabricaActionPerformed
    
    public void retornar(String nome) {
        if(nome != "") {
            String nomeClasse = listaPrototypes.getSelectedValue();
            String pacote = "prototypes";
            IPrototype prototype = (IPrototype)PluginLoader.getInstance().carregarClasse(pacote, nomeClasse);
            this.retorno.adicionar(nome, prototype);
            modalMensagem.dispose();
            adicionarSelecionado();
        }
    }
    
    private void abrirModal(CreateFactoryPrototype host) {
        modalMensagem = new Mensagem(this, Boolean.TRUE);
        modalMensagem.setMensagem("Informe um nome para o produto:");
        modalMensagem.setVisible(Boolean.TRUE);
    }
    
    public void iniciar(AbstractFactoryCar host, AbstractFactory abstractFactory) {
        this.retorno = host;
        this.abstractFactory = abstractFactory;
        PluginLoader loader = PluginLoader.getInstance();
        List<Class> listaCreators = loader.carregarPrototypes();
        listaPrototypes.setModel(new javax.swing.DefaultComboBoxModel<>(loader.getModelSelect(listaCreators, Boolean.FALSE)));
    }
    
    private void retornarHost() {
        this.retorno.retornar(this.prototype);
        this.setVisible(false);
    }
    
    private void removerTodos() {
        javax.swing.DefaultComboBoxModel<String> modelListPrototypes = (javax.swing.DefaultComboBoxModel<String>) listaPrototypes.getModel();
        javax.swing.DefaultComboBoxModel<String> modelListSelecionados = (javax.swing.DefaultComboBoxModel<String>) listaSelecionados.getModel();
        for(int i = 0; i < modelListSelecionados.getSize(); i++) {
            String adicionar = modelListSelecionados.getElementAt(i);
            modelListPrototypes.addElement(adicionar);
        }
        modelListSelecionados.removeAllElements();
    }
    
    private void adicionarSelecionado() {
        int indice = listaPrototypes.getSelectedIndex();
        javax.swing.DefaultComboBoxModel<String> modelListSelecionados = (javax.swing.DefaultComboBoxModel<String>) listaSelecionados.getModel();
        javax.swing.DefaultComboBoxModel<String> modelListPrototypes = (javax.swing.DefaultComboBoxModel<String>) listaPrototypes.getModel();
        String selecionado = modelListPrototypes.getElementAt(indice);
        modelListSelecionados.addElement(selecionado);
        modelListPrototypes.removeElement(selecionado);
    }
    
    private void removerSelecionado() {
        int indice = listaSelecionados.getSelectedIndex();
        javax.swing.DefaultComboBoxModel<String> modelListSelecionados = (javax.swing.DefaultComboBoxModel<String>) listaSelecionados.getModel();
        javax.swing.DefaultComboBoxModel<String> modelListPrototypes = (javax.swing.DefaultComboBoxModel<String>) listaPrototypes.getModel();
        String selecionado = modelListSelecionados.getElementAt(indice);
        modelListSelecionados.removeElement(selecionado);
        modelListPrototypes.addElement(selecionado);
        listaSelecionados.setSelectedIndex(-1);
        listaSelecionados.setSelectedIndices(new int[0]);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateFactoryPrototype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateFactoryPrototype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateFactoryPrototype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateFactoryPrototype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateFactoryPrototype().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarUm;
    private javax.swing.JButton btnCriarFabrica;
    private javax.swing.JButton btnRemoverTodos;
    private javax.swing.JButton btnRemoverUm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdicionar;
    private javax.swing.JLabel lblPrototypes;
    private javax.swing.JLabel lblPrototypes1;
    private javax.swing.JList<String> listaPrototypes;
    private javax.swing.JList<String> listaSelecionados;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
